# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "ehci_pci" "uhci_hcd" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/091256b0-cba2-4312-af10-0954a591d540";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/0DE8-FF3A";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/media/hdd500G" =
    { device = "/dev/disk/by-uuid/69a5598f-8145-41c4-85f6-3f75ac08bb67";
      fsType = "xfs";
    };

  fileSystems."/media/hdd1T" =
    { device = "/dev/disk/by-uuid/44ac7cc9-6b75-410a-86a5-00386a01626e";
      fsType = "xfs";
    };

  fileSystems."/media/ssd1T" =
    { device = "/dev/disk/by-uuid/221b16cd-177c-4dbd-b78a-45a415bb0372";
      fsType = "xfs";
    };

  fileSystems."/media/hdd750G" =
    { device = "/dev/disk/by-uuid/77298ab5-ab03-48ae-b26f-fc36f7f8a10b";
      fsType = "xfs";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/22943a51-d1f1-4a63-a3da-6e0c8693a165"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.docker0.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno2.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno49.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno50.useDHCP = lib.mkDefault true;
  # networking.interfaces.ovs-system.useDHCP = lib.mkDefault true;
  # networking.interfaces.sw0.useDHCP = lib.mkDefault true;
  # networking.interfaces.sw0.2.useDHCP = lib.mkDefault true;
  # networking.interfaces.sw0.3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
